In [5]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import numpy as np
categories=['alt.atheism','soc.religion.christian','comp.graphics','sci.med']
twenty_train=fetch_20newsgroups(subset='train',categories=categories,shuffle=True)
twenty_test=fetch_20newsgroups(subset='test',categories=categories,shuffle=True)
print(len(twenty_train.data))
print(len(twenty_test.data))

2257
1502


In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer

In [8]:
cv=CountVectorizer()
tf=TfidfTransformer()

In [9]:
x_train_tf=cv.fit_transform(twenty_train.data)
x_train_tfidf=tf.fit_transform(x_train_tf)

In [10]:

from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_tf = count_vect.fit_transform(twenty_train.data)
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_tf)
X_train_tfidf.shape

(2257, 35788)

In [104]:
from sklearn.naive_bayes import MultinomialNB

In [105]:
mod=MultinomialNB()
mod.fit(x_train_tfidf,twenty_train.target)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [107]:
x_test_tf=cv.transform(twenty_test.data)
x_test_tfidf=tf.transform(x_test_tf)
pre=mod.predict(x_test_tfidf)

In [108]:
print(accuracy_score(twenty_test.target,pre))

0.8348868175765646


In [109]:
print(confusion_matrix(twenty_test.target,pre))

[[192   2   6 119]
 [  2 347   4  36]
 [  2  11 322  61]
 [  2   2   1 393]]


In [110]:
print(classification_report(twenty_test.target,predicted,target_names=twenty_test.target_names))

                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

             micro avg       0.83      0.83      0.83      1502
             macro avg       0.89      0.82      0.83      1502
          weighted avg       0.88      0.83      0.84      1502

